"""Portable, escaped HTML view of the immutable result contract."""
import html
import json


def render(data):
    escape = html.escape
    serialized = json.dumps(data, ensure_ascii=False).replace("<", "\\u003c").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    gaps = "".join(f"<li>{escape(g['track'])}: {escape(g['reason'])}</li>" for g in data["quality"]["gaps"])
    frames = "".join(f'<figure><img src="frames/{escape(f["file"], quote=True)}" alt="Кадр на {f["pts_s"]:.2f} с"><figcaption>{f["pts_s"]:.2f} с · кадр {f["frame_index"]}</figcaption></figure>' for f in data["evidence"])
    return """<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Разбор рилса</title><style>
*{box-sizing:border-box}body{font:16px/1.5 system-ui;margin:0;background:#f4f5f0;color:#162725}main{max-width:1320px;margin:auto;padding:28px}h1{font-size:30px;margin:8px 0}h2{font-size:20px}.muted{color:#64726c}.grid{display:grid;grid-template-columns:300px 1fr;gap:24px}video{width:100%;height:510px;background:#101b19;border-radius:12px}aside{position:sticky;top:20px;align-self:start}.panel{background:white;border:1px solid #d8e0d9;border-radius:12px;padding:18px;margin-bottom:15px}.tracks{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.event{display:block;text-align:left;width:100%;background:#fafbf8;border:1px solid #dce3db;border-radius:8px;margin:8px 0;padding:10px;font:inherit;cursor:pointer;overflow-wrap:anywhere}.event:hover,.active{border-color:#117f6a;background:#edf7f1}.time{display:block;color:#11705f;font-size:13px}.badge{display:inline-block;background:#fff0c7;border-radius:20px;padding:4px 10px;font-size:13px}.frames{display:flex;overflow-x:auto;gap:12px}figure{margin:0;min-width:135px}img{width:135px}figcaption{font-size:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}a{color:#126f62}details{margin:15px 0}ul{padding-left:20px}@media(max-width:850px){.grid{grid-template-columns:1fr}aside{position:static}video{height:430px}.tracks{grid-template-columns:1fr}}button[disabled]{cursor:default;opacity:.7}
</style><main><p class="muted">Gemini через Antigravity · личный разбор</p><h1>Речь, экранный текст и видеоряд</h1><p><span class="badge">Обработка завершена · качество: """ + escape({"partial": "есть пробелы", "needs_review": "нужна проверка"}.get(data["quality"]["state"], data["quality"]["state"])) + """</span></p><div class="grid"><aside><video id="video" controls preload="metadata" src="video.mp4"></video><p class="muted">Модельные интервалы приблизительны. Нажми событие для перехода к фрагменту.</p><a href="analysis.json">Скачать JSON</a></aside><section><div class="panel"><h2>Общий разбор</h2><p id="summary"></p></div><div class="panel"><h2>Три дорожки разбора</h2><div class="tracks"><section><b>Речь</b><div id="speech"></div></section><section><b>Текст на экране</b><div id="text"></div></section><section><b>Картинка и переходы</b><div id="visual"></div></section></div></div><div class="panel"><h2>Ограничения и пробелы</h2><ul>""" + (gaps or "<li>Автоматические проверки пройдены. Семантическая полнота и точность требуют отдельной проверки.</li>") + """</ul><p class="muted">Уточняющие ответы не считаются независимым подтверждением.</p><div id="refinements"></div></div></section></div><section class="panel"><h2>Исходные кадры</h2><div class="frames">""" + frames + """</div></section><details class="panel"><summary>Сопоставления, материалы курса и расход</summary><pre id="details"></pre></details></main><script>
const data=""" + serialized + """;const video=document.getElementById('video');
document.getElementById('summary').textContent=data.reconciliation.summary||data.visual.summary;
function add(id,events){const area=document.getElementById(id);if(!events.length){area.textContent='Наблюдений нет';return}events.forEach(e=>{const b=document.createElement('button');b.className='event';b.type='button';if(e.start_s!=null){b.dataset.start=e.start_s;b.dataset.end=e.end_s;}const t=document.createElement('span');t.className='time';t.textContent=e.start_s==null?'Время неизвестно':e.start_s.toFixed(2)+'–'+e.end_s.toFixed(2)+' с';b.append(t);const x=document.createElement('span');x.textContent=e.text||e.description||e.appearance||'Нечитаемый текст';b.append(x);if(e.start_s==null)b.disabled=true;else b.onclick=()=>{video.currentTime=e.start_s;video.play().catch(()=>{})};area.append(b)})}
add('speech',data.speech.segments);add('text',data.visual.text_events);add('visual',data.visual.visual_events);
video.addEventListener('timeupdate',()=>document.querySelectorAll('.event[data-start]').forEach(b=>b.classList.toggle('active',video.currentTime>=Number(b.dataset.start)&&video.currentTime<=Number(b.dataset.end))));
data.refinements.forEach(r=>{const d=document.createElement('details'),s=document.createElement('summary'),p=document.createElement('pre');s.textContent='Уточнение '+r.track+' · '+r.target_gap.reason;p.textContent=JSON.stringify(r.observations,null,2);d.append(s,p);document.getElementById('refinements').append(d)});
document.getElementById('details').textContent=JSON.stringify({links:data.reconciliation.links,course:data.course,usage:data.usage,cost:data.cost},null,2);
</script></html>"""
